services:
    frontend:
        image: registry.nassimlounadi.fr/nassimlnd/salair-frontend:latest
        environment:
            NUXT_PUBLIC_API_URL: ${NUXT_PUBLIC_API_URL}
        ports:
            - '3298:3000'
        depends_on:
            - backend
        networks:
            - app_network
        restart: on-failure
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: 256M

    backend:
        image: registry.nassimlounadi.fr/nassimlnd/salair-backend:latest
        environment:
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_DATABASE: ${DB_DATABASE}
            DB_PORT: ${DB_PORT}
            HOST: ${HOST}
            TZ: ${TZ}
            PORT: ${PORT}
            LOG_LEVEL: ${LOG_LEVEL}
            APP_KEY: ${APP_KEY}
            NODE_ENV: ${NODE_ENV}
            SESSION_DRIVER: ${SESSION_DRIVER}
            DRIVE_DISK: ${DRIVE_DISK}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_REGION: ${AWS_REGION}
            S3_BUCKET: ${S3_BUCKET}
            S3_ENDPOINT: ${S3_ENDPOINT}
            PUBLIC_BUCKET_URL: ${PUBLIC_BUCKET_URL}
            MAILGUN_API_KEY: ${MAILGUN_API_KEY}
            MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
            GITHUB_TOKEN: ${GITHUB_TOKEN}
        ports:
            - '3299:3333'
        depends_on:
            - db
        networks:
            - app_network
        restart: on-failure
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M

    db:
        image: postgres:17
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        networks:
            - app_network
        restart: unless-stopped

volumes:
    db_data:

networks:
    app_network:
        driver: bridge
