services:
    db:
        image: postgres:17
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5432:5432"

    web:
        build:
            context: frontend
            dockerfile: Dockerfile
            target: main
        ports:
            - "3000:3000"

    api:
        build:
            context: backend
            dockerfile: Dockerfile
            target: main
        ports:
            - "3333:3333"
        depends_on:
            - db
        environment:
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_DATABASE: ${DB_DATABASE}
