name: Auto version, build and deploy (PROD)

on:
  push:
    branches:
      - main

concurrency:
  group: auto-tag-deploy
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  auto_tag:
    name: Auto-tag new version
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "latest_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump version (patch)
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          old=${{ steps.get_tag.outputs.latest_tag }}
          echo "Old tag: $old"

          # Remove 'v' and split version
          ver=${old#v}
          IFS='.' read -r major minor patch <<< "$ver"

          # Bump patch
          patch=$((patch + 1))
          new_tag="v$major.$minor.$patch"

          echo "New tag: $new_tag"

          git config user.name "Nassim LOUNADI"
          git config user.email "nassimlnd37@gmail.com"

          git tag "$new_tag"
          git push https://nassimlnd:${GITHUB_TOKEN}@github.com/${{ github.repository }} "$new_tag"

          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
  
  build_and_deploy:
    needs: auto_tag
    uses: ./.github/workflows/deploy-tagged.yml
    with:
      tag: ${{ needs.auto_tag.outputs.new_tag }}
    secrets: inherit
      